#!/bin/sh
# wrapper to simply pass all to aic-lib
# defined as 2 letter commands 676 options (+ flags)
# show help if no args
[ $# -eq 0 ] && cat << EOF && exit 0
archinstall-contrib

Commands:
  co [-c] <user> <repo> [branch]    - collab    Collaborate on forks/branches
  cu <user> <repo>                  - curl      Runs runme piped to bash directly

  rs                                - rescue    Inject rescue mod into archinstall
  gw                                - gitwrap   Git branch operations

Usage: ac something
EOF

##commandsm##
[ "$1" = "co" ] && set -- "collab" "${@:2}"
[ "$1" = "gw" ] && set -- "gitwrap" "${@:2}"
[ "$1" = "rs" ] && set -- "rescue" "${@:2}"
[ "$1" = "cu" ] && set -- "curl" "${@:2}"

"/usr/lib/ac/$@"
