#!/bin/sh
# wrapper to simply pass all to aic-lib
# defined as 2 letter commands 676 options (+ flags)
# show help if no args
[ $# -eq 0 ] && cat << EOF && exit 0
archinstall-contrib

Commands:
  co  - collab    Collaborate on forks/branches
  gw  - gitwrap   Git branch operations
  rs  - rescue    Mount and chroot into existing installation

Usage: aic <command> [args]
EOF

##commandsm##
[ "$1" = "co" ] && set -- "collab" "${@:2}"
[ "$1" = "gw" ] && set -- "gitwrap" "${@:2}"
[ "$1" = "rs" ] && set -- "rescue" "${@:2}"
"./aic-lib/$@"
