#!/bin/sh
# wrapper to simply pass all to aic-lib
# defined as 2 letter commands 676 options (+ flags)
# show help if no args
[ $# -eq 0 ] && cat << EOF && exit 0
archinstall-contrib

Commands:
  rs                                - rescue    Inject rescue mod into archinstall

Usage: mods <something>
EOF

##commandsm##
arg1="$1"
[ "$arg1" = "rs" ] && arg1="rescue"
shift

cmd="/usr/lib/ac/$arg1"
[ ! -f "$cmd" ] && echo "Error: Unknown command '$arg1'" && exit 1
"$cmd" "$@"
