#!/bin/sh

##constants##
# less typing more working
dev_flags=(--debug --verbose)
# adapt if using gitlab or other
provider="https://github.com"
#############

# usage collab <user> <repo> [branch]
# examples
# collab archlinux archinstall master
# collab h8d13 archinstall-patch dot-algo
# if not branch is provided we remove the -b altogether from constructor

# Determine target directory and branch
if [ -n "$3" ]; then
    target_dir="$3"
    branch_arg="-b $3"
else
    target_dir="$2"
    branch_arg=""
fi

# ensure we clone fresh delete if present
if [ -d "$target_dir" ]; then
    sudo rm -rf "$target_dir"; echo "Cleaned $target_dir"
fi

git clone $branch_arg "$provider/$1/$2" "$target_dir"

cd "$target_dir" || exit 1
sudo python -m archinstall "${dev_flags[@]}"