#!/bin/sh

##constants##
# less typing more working
dev_flags=(--debug --verbose)
# adapt if using gitlab or other
provider="https://github.com"
#############

# usage collab [-c] <user> <repo> [branch]
# -c: clean up clone after use
# examples
# collab archlinux archinstall master
# collab -c h8d13 archinstall-patch dot-resume
# if not branch is provided we remove the -b altogether from constructor

# parse clean flag
clean_after=0
[ "$1" = "-c" ] && clean_after=1 && shift

# determine we have at least arg1 | arg2
[ $# -lt 2 ] && echo "Usage: collab [-c] <user> <repo> [branch]" >&2 && exit 1

# Determine target directory and branch
if [ -n "$3" ]; then
    target_dir="$3"
    branch_arg="-b $3"
else
    target_dir="$2"
    branch_arg=""
fi

# ensure we clone fresh delete if present
if [ -d "$target_dir" ]; then
    sudo rm -rf "$target_dir"; echo "Cleaned $target_dir"
fi

git clone $branch_arg "$provider/$1/$2" "$target_dir"

cd "$target_dir" || exit 1
sudo python -m archinstall "${dev_flags[@]}"

# cleanup if flag was set
[ $clean_after -eq 1 ] && cd .. && sudo rm -rf "$target_dir" && echo "Cleaned up $target_dir"